<p>捕获 <code>Exception</code> 似乎是处理多个可能异常的有效方法。不幸的是，它会捕获所有异常类型，包括已检查和运行时异常，从而构建过于宽泛的网络。实际上，开发人员是否真的想捕获运行时异常？为了防止任何误解，如果确实要捕获已检查和运行时异常，则应在<code>catch</code> 子句中明确列出它们。</p>
<p>就是说如果 <code>try</code>块中的方法没有明显地（显式地）抛出<code>Exception</code> ，则此规则会引发问题。</p>
<h2>不合规的代码示例</h2>
<pre>
try {
  // do something that might throw an UnsupportedDataTypeException or UnsupportedEncodingException
} catch (Exception e) { // 不合规的
  // log exception ...
}
</pre>
<h2>合规的解决方案</h2>
<pre>
try {
  // do something
} catch (UnsupportedEncodingException|UnsupportedDataTypeException|RuntimeException e) {
  // log exception ...
}
</pre>
<p>or if runtime exceptions should not be caught:</p>
<pre>
try {
  // do something
} catch (UnsupportedEncodingException|UnsupportedDataTypeException e) {
  // log exception ...
}
</pre>
<h2>请详见</h2>
<ul>
  <li> <a href="http://cwe.mitre.org/data/definitions/396.html">MITRE, CWE-396</a> - Declaration of Catch for Generic Exception </li>
</ul>

